void CopyMCTree(string inputfile, string outfile) {
// Example of Root macro to copy a subset of a Tree to a new Tree
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 1 1
//Author: Rene Brun
   
	TFile *inFile = TFile::Open(inputfile.c_str());
	TTree *eventTree     = (TTree*)inFile->Get("ggHiNtuplizer/EventTree");




   // Event *event   = new Event();
   // eventTree->SetBranchAddress("event",&event);
   eventTree->SetBranchStatus("*",0);
   eventTree->SetBranchStatus("nEle",1);
   eventTree->SetBranchStatus("elePt",1);
   eventTree->SetBranchStatus("eleEta",1);
   eventTree->SetBranchStatus("elePhi",1);
   eventTree->SetBranchStatus("eleCharge",1);
   eventTree->SetBranchStatus("nMu",1);
   eventTree->SetBranchStatus("muPt",1);
   eventTree->SetBranchStatus("muEta",1);
   eventTree->SetBranchStatus("muPhi",1);
   eventTree->SetBranchStatus("muCharge",1);  
   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile(outfile.c_str(),"recreate");
   TTree *newtree = eventTree->CloneTree();

   newtree->Print();
   newfile->Write();
   delete inFile;
   delete newfile;
}
